### ISSUE TITLE
Open Code of Conduct.

### ISSUE THREAD

**Issue by davemackintosh** [Strider-CD/core#3]
We should really have a code of conduct to make open source contributions more accessible. I really recommend http://todogroup.org/opencodeofconduct

**Comment by knownasilya** [comment]
@davemackintosh can you tackle this?

**Comment by davemackintosh** [comment]
Sure can, what address should abuse reports go to? abuse@stridercd.com?

**Comment by knownasilya** [comment]
cc @niallo

**Comment by davemackintosh** [comment]
I've created the file, can update the address if it's incorrect

**Comment by niallo** [comment]
I can point the abuse emails at my own address to handle them. What do you
guys think?

On Wednesday, July 22, 2015, Dave Mackintosh notifications@github.com
wrote:

> /play deeper
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Strider-CD/core/issues/3#issuecomment-123815382.

## 

Niall O'Higgins
W: http://niallohiggins.com
E: n@niallo.me
T: @niallohiggins

**Comment by knownasilya** [comment]
Fine with me.

**Comment by niallo** [comment]
ok, abuse@stridercd.com is now a valid email address.

On Wed, Jul 22, 2015 at 1:37 PM, Ilya Radchenko notifications@github.com
wrote:

> Fine with me.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Strider-CD/core/issues/3#issuecomment-123854617.

## 

Niall O'Higgins
W: http://niallohiggins.com
E: n@niallo.me
T: @niallohiggins

**Comment by knownasilya** [comment]
Changed
