### ISSUE TITLE
Syntax Style

### ISSUE THREAD

**Issue by knownasilya** [Strider-CD/core#5]
I've started using [standard](https://github.com/feross/standard) which is a full package with no options. It is pretty standard, except for the possible use of no semicolons. The reason I chose this is so we can just start working, and so that we can have people contributing without wondering what standard to follow. There are less reasons not to use semicolons then there are to use them. See the link above, and let me know if this sounds acceptable.

The alternative would be to adopt an existing ESLint config (and maybe tweak).

**Comment by microadam** [comment]
No Semi colons is definitely the way forward. There are so few times when you actually need to use them, they just litter the code. As long as you know when to use them, you are fine. Even if you don't, you will soon know you need to when you get an error. 

This is coming from my experience of  having written many thousands of lines of code without semi colons

**Comment by knownasilya** [comment]
I'm just going to close this since it doesn't seem like anyone really has any beef with it :wink:
